/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bluefin

import (
	"encoding/json"
)

// checks if the ServiceGetInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceGetInstance{}

// ServiceGetInstance struct for ServiceGetInstance
type ServiceGetInstance struct {
	Id                   *ServiceGetInstance0 `json:"id,omitempty"`
	QueryOptions         *ServiceGetInstance1 `json:"query-options,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceGetInstance ServiceGetInstance

// NewServiceGetInstance instantiates a new ServiceGetInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceGetInstance() *ServiceGetInstance {
	this := ServiceGetInstance{}
	var queryOptions ServiceGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// NewServiceGetInstanceWithDefaults instantiates a new ServiceGetInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceGetInstanceWithDefaults() *ServiceGetInstance {
	this := ServiceGetInstance{}
	var queryOptions ServiceGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServiceGetInstance) GetId() ServiceGetInstance0 {
	if o == nil || IsNil(o.Id) {
		var ret ServiceGetInstance0
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceGetInstance) GetIdOk() (*ServiceGetInstance0, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServiceGetInstance) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given ServiceGetInstance0 and assigns it to the Id field.
func (o *ServiceGetInstance) SetId(v ServiceGetInstance0) {
	o.Id = &v
}

// GetQueryOptions returns the QueryOptions field value if set, zero value otherwise.
func (o *ServiceGetInstance) GetQueryOptions() ServiceGetInstance1 {
	if o == nil || IsNil(o.QueryOptions) {
		var ret ServiceGetInstance1
		return ret
	}
	return *o.QueryOptions
}

// GetQueryOptionsOk returns a tuple with the QueryOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceGetInstance) GetQueryOptionsOk() (*ServiceGetInstance1, bool) {
	if o == nil || IsNil(o.QueryOptions) {
		return nil, false
	}
	return o.QueryOptions, true
}

// HasQueryOptions returns a boolean if a field has been set.
func (o *ServiceGetInstance) HasQueryOptions() bool {
	if o != nil && !IsNil(o.QueryOptions) {
		return true
	}

	return false
}

// SetQueryOptions gets a reference to the given ServiceGetInstance1 and assigns it to the QueryOptions field.
func (o *ServiceGetInstance) SetQueryOptions(v ServiceGetInstance1) {
	o.QueryOptions = &v
}

func (o ServiceGetInstance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceGetInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.QueryOptions) {
		toSerialize["query-options"] = o.QueryOptions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceGetInstance) UnmarshalJSON(bytes []byte) (err error) {
	varServiceGetInstance := _ServiceGetInstance{}

	if err = json.Unmarshal(bytes, &varServiceGetInstance); err == nil {
		*o = ServiceGetInstance(varServiceGetInstance)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "query-options")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceGetInstance struct {
	value *ServiceGetInstance
	isSet bool
}

func (v NullableServiceGetInstance) Get() *ServiceGetInstance {
	return v.value
}

func (v *NullableServiceGetInstance) Set(val *ServiceGetInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceGetInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceGetInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceGetInstance(val *ServiceGetInstance) *NullableServiceGetInstance {
	return &NullableServiceGetInstance{value: val, isSet: true}
}

func (v NullableServiceGetInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceGetInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
