/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bluefin

import (
	"encoding/json"
)

// checks if the IscsiTargetGetInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IscsiTargetGetInstance{}

// IscsiTargetGetInstance struct for IscsiTargetGetInstance
type IscsiTargetGetInstance struct {
	Id                   *IscsiTargetGetInstance0 `json:"id,omitempty"`
	QueryOptions         *IscsiTargetGetInstance1 `json:"query-options,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IscsiTargetGetInstance IscsiTargetGetInstance

// NewIscsiTargetGetInstance instantiates a new IscsiTargetGetInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIscsiTargetGetInstance() *IscsiTargetGetInstance {
	this := IscsiTargetGetInstance{}
	var queryOptions IscsiTargetGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// NewIscsiTargetGetInstanceWithDefaults instantiates a new IscsiTargetGetInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIscsiTargetGetInstanceWithDefaults() *IscsiTargetGetInstance {
	this := IscsiTargetGetInstance{}
	var queryOptions IscsiTargetGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IscsiTargetGetInstance) GetId() IscsiTargetGetInstance0 {
	if o == nil || IsNil(o.Id) {
		var ret IscsiTargetGetInstance0
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiTargetGetInstance) GetIdOk() (*IscsiTargetGetInstance0, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IscsiTargetGetInstance) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given IscsiTargetGetInstance0 and assigns it to the Id field.
func (o *IscsiTargetGetInstance) SetId(v IscsiTargetGetInstance0) {
	o.Id = &v
}

// GetQueryOptions returns the QueryOptions field value if set, zero value otherwise.
func (o *IscsiTargetGetInstance) GetQueryOptions() IscsiTargetGetInstance1 {
	if o == nil || IsNil(o.QueryOptions) {
		var ret IscsiTargetGetInstance1
		return ret
	}
	return *o.QueryOptions
}

// GetQueryOptionsOk returns a tuple with the QueryOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiTargetGetInstance) GetQueryOptionsOk() (*IscsiTargetGetInstance1, bool) {
	if o == nil || IsNil(o.QueryOptions) {
		return nil, false
	}
	return o.QueryOptions, true
}

// HasQueryOptions returns a boolean if a field has been set.
func (o *IscsiTargetGetInstance) HasQueryOptions() bool {
	if o != nil && !IsNil(o.QueryOptions) {
		return true
	}

	return false
}

// SetQueryOptions gets a reference to the given IscsiTargetGetInstance1 and assigns it to the QueryOptions field.
func (o *IscsiTargetGetInstance) SetQueryOptions(v IscsiTargetGetInstance1) {
	o.QueryOptions = &v
}

func (o IscsiTargetGetInstance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IscsiTargetGetInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.QueryOptions) {
		toSerialize["query-options"] = o.QueryOptions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IscsiTargetGetInstance) UnmarshalJSON(bytes []byte) (err error) {
	varIscsiTargetGetInstance := _IscsiTargetGetInstance{}

	if err = json.Unmarshal(bytes, &varIscsiTargetGetInstance); err == nil {
		*o = IscsiTargetGetInstance(varIscsiTargetGetInstance)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "query-options")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIscsiTargetGetInstance struct {
	value *IscsiTargetGetInstance
	isSet bool
}

func (v NullableIscsiTargetGetInstance) Get() *IscsiTargetGetInstance {
	return v.value
}

func (v *NullableIscsiTargetGetInstance) Set(val *IscsiTargetGetInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableIscsiTargetGetInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableIscsiTargetGetInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIscsiTargetGetInstance(val *IscsiTargetGetInstance) *NullableIscsiTargetGetInstance {
	return &NullableIscsiTargetGetInstance{value: val, isSet: true}
}

func (v NullableIscsiTargetGetInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIscsiTargetGetInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
