/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bluefin

import (
	"encoding/json"
)

// checks if the ServiceStop type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceStop{}

// ServiceStop struct for ServiceStop
type ServiceStop struct {
	Service              *string       `json:"service,omitempty"`
	ServiceControl       *ServiceStop1 `json:"service-control,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceStop ServiceStop

// NewServiceStop instantiates a new ServiceStop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceStop() *ServiceStop {
	this := ServiceStop{}
	var serviceControl ServiceStop1
	this.ServiceControl = &serviceControl
	return &this
}

// NewServiceStopWithDefaults instantiates a new ServiceStop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceStopWithDefaults() *ServiceStop {
	this := ServiceStop{}
	var serviceControl ServiceStop1
	this.ServiceControl = &serviceControl
	return &this
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *ServiceStop) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceStop) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *ServiceStop) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *ServiceStop) SetService(v string) {
	o.Service = &v
}

// GetServiceControl returns the ServiceControl field value if set, zero value otherwise.
func (o *ServiceStop) GetServiceControl() ServiceStop1 {
	if o == nil || IsNil(o.ServiceControl) {
		var ret ServiceStop1
		return ret
	}
	return *o.ServiceControl
}

// GetServiceControlOk returns a tuple with the ServiceControl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceStop) GetServiceControlOk() (*ServiceStop1, bool) {
	if o == nil || IsNil(o.ServiceControl) {
		return nil, false
	}
	return o.ServiceControl, true
}

// HasServiceControl returns a boolean if a field has been set.
func (o *ServiceStop) HasServiceControl() bool {
	if o != nil && !IsNil(o.ServiceControl) {
		return true
	}

	return false
}

// SetServiceControl gets a reference to the given ServiceStop1 and assigns it to the ServiceControl field.
func (o *ServiceStop) SetServiceControl(v ServiceStop1) {
	o.ServiceControl = &v
}

func (o ServiceStop) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceStop) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.ServiceControl) {
		toSerialize["service-control"] = o.ServiceControl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceStop) UnmarshalJSON(bytes []byte) (err error) {
	varServiceStop := _ServiceStop{}

	if err = json.Unmarshal(bytes, &varServiceStop); err == nil {
		*o = ServiceStop(varServiceStop)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "service")
		delete(additionalProperties, "service-control")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceStop struct {
	value *ServiceStop
	isSet bool
}

func (v NullableServiceStop) Get() *ServiceStop {
	return v.value
}

func (v *NullableServiceStop) Set(val *ServiceStop) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceStop) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceStop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceStop(val *ServiceStop) *NullableServiceStop {
	return &NullableServiceStop{value: val, isSet: true}
}

func (v NullableServiceStop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceStop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
