/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bluefin

import (
	"encoding/json"
)

// checks if the KubernetesRestoreBackup1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KubernetesRestoreBackup1{}

// KubernetesRestoreBackup1 struct for KubernetesRestoreBackup1
type KubernetesRestoreBackup1 struct {
	WaitForCsi *bool `json:"wait_for_csi,omitempty"`
}

// NewKubernetesRestoreBackup1 instantiates a new KubernetesRestoreBackup1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubernetesRestoreBackup1() *KubernetesRestoreBackup1 {
	this := KubernetesRestoreBackup1{}
	var waitForCsi bool
	this.WaitForCsi = &waitForCsi
	return &this
}

// NewKubernetesRestoreBackup1WithDefaults instantiates a new KubernetesRestoreBackup1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubernetesRestoreBackup1WithDefaults() *KubernetesRestoreBackup1 {
	this := KubernetesRestoreBackup1{}
	var waitForCsi bool
	this.WaitForCsi = &waitForCsi
	return &this
}

// GetWaitForCsi returns the WaitForCsi field value if set, zero value otherwise.
func (o *KubernetesRestoreBackup1) GetWaitForCsi() bool {
	if o == nil || IsNil(o.WaitForCsi) {
		var ret bool
		return ret
	}
	return *o.WaitForCsi
}

// GetWaitForCsiOk returns a tuple with the WaitForCsi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubernetesRestoreBackup1) GetWaitForCsiOk() (*bool, bool) {
	if o == nil || IsNil(o.WaitForCsi) {
		return nil, false
	}
	return o.WaitForCsi, true
}

// HasWaitForCsi returns a boolean if a field has been set.
func (o *KubernetesRestoreBackup1) HasWaitForCsi() bool {
	if o != nil && !IsNil(o.WaitForCsi) {
		return true
	}

	return false
}

// SetWaitForCsi gets a reference to the given bool and assigns it to the WaitForCsi field.
func (o *KubernetesRestoreBackup1) SetWaitForCsi(v bool) {
	o.WaitForCsi = &v
}

func (o KubernetesRestoreBackup1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KubernetesRestoreBackup1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WaitForCsi) {
		toSerialize["wait_for_csi"] = o.WaitForCsi
	}
	return toSerialize, nil
}

type NullableKubernetesRestoreBackup1 struct {
	value *KubernetesRestoreBackup1
	isSet bool
}

func (v NullableKubernetesRestoreBackup1) Get() *KubernetesRestoreBackup1 {
	return v.value
}

func (v *NullableKubernetesRestoreBackup1) Set(val *KubernetesRestoreBackup1) {
	v.value = val
	v.isSet = true
}

func (v NullableKubernetesRestoreBackup1) IsSet() bool {
	return v.isSet
}

func (v *NullableKubernetesRestoreBackup1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubernetesRestoreBackup1(val *KubernetesRestoreBackup1) *NullableKubernetesRestoreBackup1 {
	return &NullableKubernetesRestoreBackup1{value: val, isSet: true}
}

func (v NullableKubernetesRestoreBackup1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubernetesRestoreBackup1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
