/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bluefin

import (
	"encoding/json"
)

// checks if the ContainerUpdate0 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerUpdate0{}

// ContainerUpdate0 struct for ContainerUpdate0
type ContainerUpdate0 struct {
	EnableImageUpdates *bool `json:"enable_image_updates,omitempty"`
}

// NewContainerUpdate0 instantiates a new ContainerUpdate0 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerUpdate0() *ContainerUpdate0 {
	this := ContainerUpdate0{}
	return &this
}

// NewContainerUpdate0WithDefaults instantiates a new ContainerUpdate0 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerUpdate0WithDefaults() *ContainerUpdate0 {
	this := ContainerUpdate0{}
	return &this
}

// GetEnableImageUpdates returns the EnableImageUpdates field value if set, zero value otherwise.
func (o *ContainerUpdate0) GetEnableImageUpdates() bool {
	if o == nil || IsNil(o.EnableImageUpdates) {
		var ret bool
		return ret
	}
	return *o.EnableImageUpdates
}

// GetEnableImageUpdatesOk returns a tuple with the EnableImageUpdates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerUpdate0) GetEnableImageUpdatesOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableImageUpdates) {
		return nil, false
	}
	return o.EnableImageUpdates, true
}

// HasEnableImageUpdates returns a boolean if a field has been set.
func (o *ContainerUpdate0) HasEnableImageUpdates() bool {
	if o != nil && !IsNil(o.EnableImageUpdates) {
		return true
	}

	return false
}

// SetEnableImageUpdates gets a reference to the given bool and assigns it to the EnableImageUpdates field.
func (o *ContainerUpdate0) SetEnableImageUpdates(v bool) {
	o.EnableImageUpdates = &v
}

func (o ContainerUpdate0) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerUpdate0) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EnableImageUpdates) {
		toSerialize["enable_image_updates"] = o.EnableImageUpdates
	}
	return toSerialize, nil
}

type NullableContainerUpdate0 struct {
	value *ContainerUpdate0
	isSet bool
}

func (v NullableContainerUpdate0) Get() *ContainerUpdate0 {
	return v.value
}

func (v *NullableContainerUpdate0) Set(val *ContainerUpdate0) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerUpdate0) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerUpdate0) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerUpdate0(val *ContainerUpdate0) *NullableContainerUpdate0 {
	return &NullableContainerUpdate0{value: val, isSet: true}
}

func (v NullableContainerUpdate0) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerUpdate0) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
