/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bluefin

import (
	"encoding/json"
)

// checks if the CtdbPrivateIpsGetInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CtdbPrivateIpsGetInstance{}

// CtdbPrivateIpsGetInstance struct for CtdbPrivateIpsGetInstance
type CtdbPrivateIpsGetInstance struct {
	Id                   *CtdbPrivateIpsGetInstance0 `json:"id,omitempty"`
	QueryOptions         *CtdbPrivateIpsGetInstance1 `json:"query-options,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CtdbPrivateIpsGetInstance CtdbPrivateIpsGetInstance

// NewCtdbPrivateIpsGetInstance instantiates a new CtdbPrivateIpsGetInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCtdbPrivateIpsGetInstance() *CtdbPrivateIpsGetInstance {
	this := CtdbPrivateIpsGetInstance{}
	var queryOptions CtdbPrivateIpsGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// NewCtdbPrivateIpsGetInstanceWithDefaults instantiates a new CtdbPrivateIpsGetInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCtdbPrivateIpsGetInstanceWithDefaults() *CtdbPrivateIpsGetInstance {
	this := CtdbPrivateIpsGetInstance{}
	var queryOptions CtdbPrivateIpsGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CtdbPrivateIpsGetInstance) GetId() CtdbPrivateIpsGetInstance0 {
	if o == nil || IsNil(o.Id) {
		var ret CtdbPrivateIpsGetInstance0
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CtdbPrivateIpsGetInstance) GetIdOk() (*CtdbPrivateIpsGetInstance0, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CtdbPrivateIpsGetInstance) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given CtdbPrivateIpsGetInstance0 and assigns it to the Id field.
func (o *CtdbPrivateIpsGetInstance) SetId(v CtdbPrivateIpsGetInstance0) {
	o.Id = &v
}

// GetQueryOptions returns the QueryOptions field value if set, zero value otherwise.
func (o *CtdbPrivateIpsGetInstance) GetQueryOptions() CtdbPrivateIpsGetInstance1 {
	if o == nil || IsNil(o.QueryOptions) {
		var ret CtdbPrivateIpsGetInstance1
		return ret
	}
	return *o.QueryOptions
}

// GetQueryOptionsOk returns a tuple with the QueryOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CtdbPrivateIpsGetInstance) GetQueryOptionsOk() (*CtdbPrivateIpsGetInstance1, bool) {
	if o == nil || IsNil(o.QueryOptions) {
		return nil, false
	}
	return o.QueryOptions, true
}

// HasQueryOptions returns a boolean if a field has been set.
func (o *CtdbPrivateIpsGetInstance) HasQueryOptions() bool {
	if o != nil && !IsNil(o.QueryOptions) {
		return true
	}

	return false
}

// SetQueryOptions gets a reference to the given CtdbPrivateIpsGetInstance1 and assigns it to the QueryOptions field.
func (o *CtdbPrivateIpsGetInstance) SetQueryOptions(v CtdbPrivateIpsGetInstance1) {
	o.QueryOptions = &v
}

func (o CtdbPrivateIpsGetInstance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CtdbPrivateIpsGetInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.QueryOptions) {
		toSerialize["query-options"] = o.QueryOptions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CtdbPrivateIpsGetInstance) UnmarshalJSON(bytes []byte) (err error) {
	varCtdbPrivateIpsGetInstance := _CtdbPrivateIpsGetInstance{}

	if err = json.Unmarshal(bytes, &varCtdbPrivateIpsGetInstance); err == nil {
		*o = CtdbPrivateIpsGetInstance(varCtdbPrivateIpsGetInstance)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "query-options")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCtdbPrivateIpsGetInstance struct {
	value *CtdbPrivateIpsGetInstance
	isSet bool
}

func (v NullableCtdbPrivateIpsGetInstance) Get() *CtdbPrivateIpsGetInstance {
	return v.value
}

func (v *NullableCtdbPrivateIpsGetInstance) Set(val *CtdbPrivateIpsGetInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableCtdbPrivateIpsGetInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableCtdbPrivateIpsGetInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCtdbPrivateIpsGetInstance(val *CtdbPrivateIpsGetInstance) *NullableCtdbPrivateIpsGetInstance {
	return &NullableCtdbPrivateIpsGetInstance{value: val, isSet: true}
}

func (v NullableCtdbPrivateIpsGetInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCtdbPrivateIpsGetInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
