/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bluefin

import (
	"encoding/json"
)

// checks if the CertificateGetInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateGetInstance{}

// CertificateGetInstance struct for CertificateGetInstance
type CertificateGetInstance struct {
	Id                   *CertificateGetInstance0 `json:"id,omitempty"`
	QueryOptions         *CertificateGetInstance1 `json:"query-options,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CertificateGetInstance CertificateGetInstance

// NewCertificateGetInstance instantiates a new CertificateGetInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateGetInstance() *CertificateGetInstance {
	this := CertificateGetInstance{}
	var queryOptions CertificateGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// NewCertificateGetInstanceWithDefaults instantiates a new CertificateGetInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateGetInstanceWithDefaults() *CertificateGetInstance {
	this := CertificateGetInstance{}
	var queryOptions CertificateGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CertificateGetInstance) GetId() CertificateGetInstance0 {
	if o == nil || IsNil(o.Id) {
		var ret CertificateGetInstance0
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateGetInstance) GetIdOk() (*CertificateGetInstance0, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CertificateGetInstance) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given CertificateGetInstance0 and assigns it to the Id field.
func (o *CertificateGetInstance) SetId(v CertificateGetInstance0) {
	o.Id = &v
}

// GetQueryOptions returns the QueryOptions field value if set, zero value otherwise.
func (o *CertificateGetInstance) GetQueryOptions() CertificateGetInstance1 {
	if o == nil || IsNil(o.QueryOptions) {
		var ret CertificateGetInstance1
		return ret
	}
	return *o.QueryOptions
}

// GetQueryOptionsOk returns a tuple with the QueryOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateGetInstance) GetQueryOptionsOk() (*CertificateGetInstance1, bool) {
	if o == nil || IsNil(o.QueryOptions) {
		return nil, false
	}
	return o.QueryOptions, true
}

// HasQueryOptions returns a boolean if a field has been set.
func (o *CertificateGetInstance) HasQueryOptions() bool {
	if o != nil && !IsNil(o.QueryOptions) {
		return true
	}

	return false
}

// SetQueryOptions gets a reference to the given CertificateGetInstance1 and assigns it to the QueryOptions field.
func (o *CertificateGetInstance) SetQueryOptions(v CertificateGetInstance1) {
	o.QueryOptions = &v
}

func (o CertificateGetInstance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateGetInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.QueryOptions) {
		toSerialize["query-options"] = o.QueryOptions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CertificateGetInstance) UnmarshalJSON(bytes []byte) (err error) {
	varCertificateGetInstance := _CertificateGetInstance{}

	if err = json.Unmarshal(bytes, &varCertificateGetInstance); err == nil {
		*o = CertificateGetInstance(varCertificateGetInstance)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "query-options")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCertificateGetInstance struct {
	value *CertificateGetInstance
	isSet bool
}

func (v NullableCertificateGetInstance) Get() *CertificateGetInstance {
	return v.value
}

func (v *NullableCertificateGetInstance) Set(val *CertificateGetInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateGetInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateGetInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateGetInstance(val *CertificateGetInstance) *NullableCertificateGetInstance {
	return &NullableCertificateGetInstance{value: val, isSet: true}
}

func (v NullableCertificateGetInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateGetInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
