/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bluefin

import (
	"encoding/json"
)

// checks if the IscsiInitiatorGetInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IscsiInitiatorGetInstance{}

// IscsiInitiatorGetInstance struct for IscsiInitiatorGetInstance
type IscsiInitiatorGetInstance struct {
	Id                   *IscsiInitiatorGetInstance0 `json:"id,omitempty"`
	QueryOptions         *IscsiInitiatorGetInstance1 `json:"query-options,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IscsiInitiatorGetInstance IscsiInitiatorGetInstance

// NewIscsiInitiatorGetInstance instantiates a new IscsiInitiatorGetInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIscsiInitiatorGetInstance() *IscsiInitiatorGetInstance {
	this := IscsiInitiatorGetInstance{}
	var queryOptions IscsiInitiatorGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// NewIscsiInitiatorGetInstanceWithDefaults instantiates a new IscsiInitiatorGetInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIscsiInitiatorGetInstanceWithDefaults() *IscsiInitiatorGetInstance {
	this := IscsiInitiatorGetInstance{}
	var queryOptions IscsiInitiatorGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IscsiInitiatorGetInstance) GetId() IscsiInitiatorGetInstance0 {
	if o == nil || IsNil(o.Id) {
		var ret IscsiInitiatorGetInstance0
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiInitiatorGetInstance) GetIdOk() (*IscsiInitiatorGetInstance0, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IscsiInitiatorGetInstance) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given IscsiInitiatorGetInstance0 and assigns it to the Id field.
func (o *IscsiInitiatorGetInstance) SetId(v IscsiInitiatorGetInstance0) {
	o.Id = &v
}

// GetQueryOptions returns the QueryOptions field value if set, zero value otherwise.
func (o *IscsiInitiatorGetInstance) GetQueryOptions() IscsiInitiatorGetInstance1 {
	if o == nil || IsNil(o.QueryOptions) {
		var ret IscsiInitiatorGetInstance1
		return ret
	}
	return *o.QueryOptions
}

// GetQueryOptionsOk returns a tuple with the QueryOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiInitiatorGetInstance) GetQueryOptionsOk() (*IscsiInitiatorGetInstance1, bool) {
	if o == nil || IsNil(o.QueryOptions) {
		return nil, false
	}
	return o.QueryOptions, true
}

// HasQueryOptions returns a boolean if a field has been set.
func (o *IscsiInitiatorGetInstance) HasQueryOptions() bool {
	if o != nil && !IsNil(o.QueryOptions) {
		return true
	}

	return false
}

// SetQueryOptions gets a reference to the given IscsiInitiatorGetInstance1 and assigns it to the QueryOptions field.
func (o *IscsiInitiatorGetInstance) SetQueryOptions(v IscsiInitiatorGetInstance1) {
	o.QueryOptions = &v
}

func (o IscsiInitiatorGetInstance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IscsiInitiatorGetInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.QueryOptions) {
		toSerialize["query-options"] = o.QueryOptions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IscsiInitiatorGetInstance) UnmarshalJSON(bytes []byte) (err error) {
	varIscsiInitiatorGetInstance := _IscsiInitiatorGetInstance{}

	if err = json.Unmarshal(bytes, &varIscsiInitiatorGetInstance); err == nil {
		*o = IscsiInitiatorGetInstance(varIscsiInitiatorGetInstance)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "query-options")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIscsiInitiatorGetInstance struct {
	value *IscsiInitiatorGetInstance
	isSet bool
}

func (v NullableIscsiInitiatorGetInstance) Get() *IscsiInitiatorGetInstance {
	return v.value
}

func (v *NullableIscsiInitiatorGetInstance) Set(val *IscsiInitiatorGetInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableIscsiInitiatorGetInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableIscsiInitiatorGetInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIscsiInitiatorGetInstance(val *IscsiInitiatorGetInstance) *NullableIscsiInitiatorGetInstance {
	return &NullableIscsiInitiatorGetInstance{value: val, isSet: true}
}

func (v NullableIscsiInitiatorGetInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIscsiInitiatorGetInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
