/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bluefin

import (
	"encoding/json"
)

// checks if the CertificateauthorityGetInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateauthorityGetInstance{}

// CertificateauthorityGetInstance struct for CertificateauthorityGetInstance
type CertificateauthorityGetInstance struct {
	Id                   *CertificateauthorityGetInstance0 `json:"id,omitempty"`
	QueryOptions         *CertificateauthorityGetInstance1 `json:"query-options,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CertificateauthorityGetInstance CertificateauthorityGetInstance

// NewCertificateauthorityGetInstance instantiates a new CertificateauthorityGetInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateauthorityGetInstance() *CertificateauthorityGetInstance {
	this := CertificateauthorityGetInstance{}
	var queryOptions CertificateauthorityGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// NewCertificateauthorityGetInstanceWithDefaults instantiates a new CertificateauthorityGetInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateauthorityGetInstanceWithDefaults() *CertificateauthorityGetInstance {
	this := CertificateauthorityGetInstance{}
	var queryOptions CertificateauthorityGetInstance1
	this.QueryOptions = &queryOptions
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CertificateauthorityGetInstance) GetId() CertificateauthorityGetInstance0 {
	if o == nil || IsNil(o.Id) {
		var ret CertificateauthorityGetInstance0
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateauthorityGetInstance) GetIdOk() (*CertificateauthorityGetInstance0, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CertificateauthorityGetInstance) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given CertificateauthorityGetInstance0 and assigns it to the Id field.
func (o *CertificateauthorityGetInstance) SetId(v CertificateauthorityGetInstance0) {
	o.Id = &v
}

// GetQueryOptions returns the QueryOptions field value if set, zero value otherwise.
func (o *CertificateauthorityGetInstance) GetQueryOptions() CertificateauthorityGetInstance1 {
	if o == nil || IsNil(o.QueryOptions) {
		var ret CertificateauthorityGetInstance1
		return ret
	}
	return *o.QueryOptions
}

// GetQueryOptionsOk returns a tuple with the QueryOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateauthorityGetInstance) GetQueryOptionsOk() (*CertificateauthorityGetInstance1, bool) {
	if o == nil || IsNil(o.QueryOptions) {
		return nil, false
	}
	return o.QueryOptions, true
}

// HasQueryOptions returns a boolean if a field has been set.
func (o *CertificateauthorityGetInstance) HasQueryOptions() bool {
	if o != nil && !IsNil(o.QueryOptions) {
		return true
	}

	return false
}

// SetQueryOptions gets a reference to the given CertificateauthorityGetInstance1 and assigns it to the QueryOptions field.
func (o *CertificateauthorityGetInstance) SetQueryOptions(v CertificateauthorityGetInstance1) {
	o.QueryOptions = &v
}

func (o CertificateauthorityGetInstance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateauthorityGetInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.QueryOptions) {
		toSerialize["query-options"] = o.QueryOptions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CertificateauthorityGetInstance) UnmarshalJSON(bytes []byte) (err error) {
	varCertificateauthorityGetInstance := _CertificateauthorityGetInstance{}

	if err = json.Unmarshal(bytes, &varCertificateauthorityGetInstance); err == nil {
		*o = CertificateauthorityGetInstance(varCertificateauthorityGetInstance)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "query-options")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCertificateauthorityGetInstance struct {
	value *CertificateauthorityGetInstance
	isSet bool
}

func (v NullableCertificateauthorityGetInstance) Get() *CertificateauthorityGetInstance {
	return v.value
}

func (v *NullableCertificateauthorityGetInstance) Set(val *CertificateauthorityGetInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateauthorityGetInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateauthorityGetInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateauthorityGetInstance(val *CertificateauthorityGetInstance) *NullableCertificateauthorityGetInstance {
	return &NullableCertificateauthorityGetInstance{value: val, isSet: true}
}

func (v NullableCertificateauthorityGetInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateauthorityGetInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
